inherit_gem:
  rubocop-shopify: rubocop.yml

AllCops:
  TargetRubyVersion: 2.6
  NewCops: disable
  Exclude:
    - "**/extconf.rb"

Style/StringLiterals:
  EnforcedStyle: single_quotes

Style/MethodCallWithArgsParentheses:
  Enabled: true
  IgnoreMacros: false
  IgnoredMethods: []
  AllowParenthesesInMultilineCall: true
  AllowParenthesesInChaining: true
  AllowParenthesesInCamelCaseMethod: true
  AllowParenthesesInStringInterpolation: true
  EnforcedStyle: require_parentheses
